CREATE DATABASE ProductDB;
GO
USE ProductDB;
GO
CREATE TABLE PRODUCTS (
  PRODUCTID INT PRIMARY KEY IDENTITY(1,1),
  PRODUCTNAME NVARCHAR(100),
  PRICE DECIMAL(10, 2),
  STOCK INT
);
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'ProductDB')
BEGIN
    CREATE DATABASE ProductDB;
END
